wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1703056176.913338
    t:
      1:
      - 49
      - 55
      - 105
      2:
      - 49
      - 55
      - 105
      3:
      - 13
      - 23
      4: 3.11.5
      5: 0.16.1
      8:
      - 1
      - 5
      13: linux-x86_64
